### ISSUE TITLE
Welcome-file should be configurable or documented.

### ISSUE THREAD

**Issue by tp0ck3r** [tandraschko/quarkus-myfaces#19]
It took me some time to find out that I need to have index.xhtml in my web folder. I didn't have it and the old issue regarding NPE happened again. I think index.xhtml should be configurable and not hard-coded in QuarkusResourceResolver.
Thanks and regards, Tom

**Comment by tandraschko** [comment]
I will try to get rid of this completely
we just used index.xhtml to get the "root" of the resources for the JSF ResourceHandler.
I will try to workaround this, without a required welcome-file

**Comment by tp0ck3r** [comment]
Okay, many thanks! :)

**Comment by tandraschko** [comment]
fixed the NPE in MyFaces and removed the hack in quarkus-myfaces now

**Comment by tp0ck3r** [comment]
Wow, super fast, thank you!

**Comment by tandraschko** [comment]
your welcome :)
