### ISSUE TITLE
QuarkusCdiELResolver - Dependent on beans used in EL are currently not supported!

### ISSUE THREAD

**Issue by rmpestano** [tandraschko/quarkus-myfaces#2]
Hi, any special reason for this check? 
https://github.com/tandraschko/quarkus-myfaces/blob/89f7ce51fb87cf80cbc3c9a28042f840bc4b0dd7/quarkus-myfaces/runtime/src/main/java/io/quarkus/myfaces/runtime/myfaces/QuarkusCdiELResolver.java#L82-L85

I question because I'm getting this FacesException caused by org.apache.myfaces.cdi.JsfArtifactProducer

![Screenshot from 2019-05-28 13-53-35](https://user-images.githubusercontent.com/1592273/58498732-09e95280-8155-11e9-9267-748e58428ec6.png)

If I comment out this block my sample application works.

**Comment by rmpestano** [comment]
I think it comes from this el expression on my application:

```
rendered="#{not empty title and empty requestScope['javax.servlet.error.exception_type'] and empty requestScope['javax.servlet.error.message']}"
```

**Comment by tandraschko** [comment]
I Just didn't implement it because its not good performance (each EL will create a new bean instance, requestScope should be prefered) and requires some extra logic.
I wonder why requestScope is dependent. Let me check later.

**Comment by tandraschko** [comment]
fixed it now - you need to rebuild myfaces and the extension.
Still it doesn't support @Dependent for EL resolution but i also suggest to don't use it.

**Comment by rmpestano** [comment]
Working great now! thank you
