### ISSUE TITLE
Add support for native 

### ISSUE THREAD

**Issue by tandraschko** [tandraschko/quarkus-myfaces#20]
> Another problem, as Emmanuel mentioned, is that currently it doesn't work in native mode on graal vm.
We are very close to get it working (Rafael is working on it: https://github.com/rmpestano/quarkus-myfaces) but there is one big problem....
To use `@Named` beans in xhtmls, reflection is required. So actually we must create reflection metadata for quarkus for every `@Named` Bean + all public getter/setter POJOs. The native image will be very big because of this overhead.
I'm currently not sure if its worth to run it in native. However, non-native mode works fine.

**Comment by tandraschko** [comment]
JFYI: i wont invest much time here.  Rafael is working on it already but not sure how much time he has.
i already invested like 40 hours to get the quarkus support working and we are 90+% feature complete

i'm not sure if native mode is really required for a JSF application.

However, if someone needs it, feel free to provide a PR (+ contact me and rafael) or think about sponsoring it.

**Comment by rmpestano** [comment]
Yea, same here and I also would be interested in hearing the usecases for JSF on native mode.

Anyway I think we should focus on jvm mode and get It feature complete if it isn't already.

**Comment by tandraschko** [comment]
Yep, i think the only missing feature is: https://github.com/tandraschko/quarkus-myfaces/issues/15
which is quite >internal<
a normal users doesn't overwrite such internal artifacts
