### ISSUE TITLE
Set faces projectStage based in Quarkus run mod

### ISSUE THREAD

**Issue by rmpestano** [tandraschko/quarkus-myfaces#5]
It would be nice to set `javax.faces.FACELETS_REFRESH_PERIOD` to `0` when projectStage is `Development`, this could be done in [QuarkusServletContextListener](https://github.com/tandraschko/quarkus-myfaces/blob/8eb72043c1c301393138ef248ede2e833a01213c/quarkus-myfaces/runtime/src/main/java/io/quarkus/myfaces/runtime/startup/QuarkusServletContextListener.java#L30), something like:

```
@WebListener
public class QuarkusServletContextListener implements ServletContextListener {

    @ConfigProperty(name = "javax.faces.PROJECT_STAGE") //see application.properties
    String projectStage;

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        sce.getServletContext().setInitParameter("javax.faces.PROJECT_STAGE", projectStage);
        if(!ProjectStage.Production.name().equals(projectStage)) {
            sce.getServletContext().setInitParameter("javax.faces.FACELETS_REFRESH_PERIOD", "0");
        }
    }
}
``` 

Then in quarkus:dev mode we can change pages without restarting the application.

OBS: Project stage also is not being set based on application.properties so we need to set it in our on [StartupListener](https://github.com/tandraschko/quarkus-myfaces/blob/8eb72043c1c301393138ef248ede2e833a01213c/quarkus-myfaces-showcase/src/main/java/io/quarkus/myfaces/showcase/StartupListener.java#L16), like in showcase example, I think it should also be set in QuarkusServletContextListener.

WDYT?

**Comment by tandraschko** [comment]
I thought thats automatically done by the jsf impl?

**Comment by rmpestano** [comment]
Yes, the main issue was that the project stage was not being set, so changing my question, shouldn't we set the project stage in  QuarkusServletContextListener?

**Comment by tandraschko** [comment]
yep
would you like to provide a PR and also remove the logic from the showcase then?
